auth_app/urls.py
from django.urls import path
from . import views


app_name = "auth"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/", views.profile, name="profile"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("post.urls")),
    path("", include("auth_app.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path("", views.index, name="home"),
    path("add_post", views.add_post, name="add_post"),
    path("posts", views.posts, name="posts"),
    path("post/<int:id>", views.post_details, name="details"),
    path("edit_post/<int:id>", views.edit_post, name="edit_post"),
    path("delete_post/<int:id>", views.delete_post, name="delete_post")
]

auth_app/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Posts(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=126)
    content = models.TextField(max_length=1000)
    published_date = models.DateTimeField(auto_now_add=True)

auth_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib import messages

from django.contrib.auth.models import User
from post.models import Posts


# Create your views here.


def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = User.objects.filter(username=username)
        if user.exists():
            messages.error(request, "Username already taken")
            return redirect(reverse('auth:register'))

        user = User.objects.create_user(username=username, email=email)
        user.set_password(password)

        user.save()
        messages.success(request, "User Created successfully")
        return redirect(reverse('auth:login'))

    return render(request, "auth_app/register.html")


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if not User.objects.filter(username=username).exists():
            messages.error(request, "Invalid username")
            return redirect(reverse('auth:login'))

        user = authenticate(request, username=username, password=password)

        if user is None:
            messages.error(request, "invalid password")
            return redirect(reverse('auth:login'))

        else:
            login(request, user)
            return redirect(reverse('post:posts'))

    return render(request, "auth_app/login.html")


def logout_user(request):
    logout(request)
    return redirect(reverse('auth:login'))


def profile(request):
    if request.user.is_authenticated:
        user_name = request.user.username
        user = User.objects.get(username=user_name)
        print(user.id)
        posts = Posts.objects.filter(user=user)

    return render(request, "auth_app/profile.html", {
        "user": user,
        "posts": posts,
    })

post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from post.models import Posts
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.


class BlogForm(forms.Form):
    title = forms.CharField(label="Title", max_length=100)
    content = forms.CharField(widget=forms.Textarea)


def index(request):
    return redirect(reverse("post:posts"))


@login_required(login_url="auth:login")
def add_post(request):
    if request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            user = User.objects.get(username=request.user.username)
            _ = Posts(title=title, content=content, user=user)
            _.save()

            return HttpResponseRedirect(reverse("post:posts"))
    else:

        return render(request, 'post/w_posts.html', {
            "form": BlogForm
        })


def posts(request):
    posts = Posts.objects.all()
    return render(request, 'post/posts.html', {
        "posts": posts
    })


def post_details(request, id):
    if id:
        post = Posts.objects.get(pk=id)

    return render(request, 'post/details.html', {
        "post": post
    })


def edit_post(request, id):
    post = Posts.objects.get(pk=id)

    if request.method == "POST":
        post.title = request.POST.get("title")
        post.content = request.POST.get("content")
        post.save()
        return redirect('post:details', id=post.id)

    return render(request, 'post/edit_post.html', {
        "post": post,
        "form": BlogForm
    })


def delete_post(request, id):
    post = Posts.objects.get(pk=id)

    post.delete()

    return HttpResponseRedirect(reverse("auth:profile"))

auth_app/templates/auth_app/login.html
{% extends 'post/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">

{% endblock styles %}
{% block body %}

<div class="register">
    <div class="container" style="max-width: 300px;box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);">

        <form action="{% url 'auth:login'%}" method="post">
            {% csrf_token %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">
                {{message}}
            </div>
            {% endfor %}

            {% endif %}

            <div class="mb-1">
                <label for="exampleInputEmail1" class="form-label">User name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="username">

            </div>

            <div class="mb-1">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password">
            </div>
            <div class="mb-1">
                Don't have an account <a href="{% url 'auth:register' %}">register</a>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>


{% endblock body %}

auth_app/templates/auth_app/profile.html
{% include 'post/base.html' %}

{% block body %}
<div class="container">
    <h1><i>hi, {{user.username}}</i></h1>
</div>
<div class="container-md">
    <h2 style="text-align: center;"><i>your posts</i></h2>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th class="w-50">Title</th>
            <th>Published Date</th>
            <th>Action</th>

        </tr>
        {% for post in posts %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'post:details' post.id %}">{{post.title}}</a></td>
            <td>{{post.published_date.date}}</td>

            <td><button type="button" class="btn btn-primary"><a
                        href="{% url 'post:edit_post' post.id %}">Edit</a></button>
                <button type="button" class="btn btn-danger"><a
                        href="{% url 'post:delete_post' post.id %}">Delete</a></button>
            </td>

        </tr>


        {% endfor %}
    </table>

</div>

{% endblock body %}

auth_app/templates/auth_app/register.html
{% extends 'post/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">

{% endblock styles %}
{% block body %}

<div class="register">
    <div class="container" style="max-width: 300px;box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);">

        <form action="{% url 'auth:register'%}" method="post">
            {% csrf_token %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">
                {{message}}
            </div>
            {% endfor %}

            {% endif %}

            <div class="mb-1">
                <label for="exampleInputEmail1" class="form-label">User name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="username">

            </div>

            <div class="mb-1">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    name="email">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-1">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password">
            </div>
            <div class="mb-1">
                Already a member <a href="{% url 'auth:login' %}">Login</a>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock body %}

post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    {% load static %}
    {% block styles %}

    {% endblock styles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>
        {% block title %}


        {% endblock title %}
    </title>

</head>

<body>

    {% include 'post/navbar.html' %}


    {% block body %}

    {% endblock body %}

</body>

</html>

post/templates/post/details.html
{% extends 'post/base.html' %}


{% block body %}
<div class="container-sm" style="background-color: antiquewhite; margin-top:10px">
    <h1 style="text-align: center;"><i>{{post.title}}</i></h1>
    <h6 class="card-subtitle mb-2 text-muted">{{post.published_date.date}}</h6>
    <h6 class="card-subtitle mb-2 text-muted">By {{post.user}}</h6>

    <hr>
    <div>
        <p style="padding-bottom: 10px;"">
            {{post.content|safe }}
        </p>
    </div>




</div>

{% endblock body %}

post/templates/post/edit_post.html
{% extends 'post/base.html' %}

{% block body %}
<div class="container-md">

    <form action="{% url 'post:edit_post' post.id %}" method="post">
        {% csrf_token %}
        <br>
        <div class="row justify-content-md-center"><input type="text" name="title" value="{{post.title}}"></div>
        <br>
        <div class="row justify-content-md-center">
            <textarea name="content" cols="30" rows="10">
                {{post.content}}
            </textarea>
        </div>
        <br>
        <button type="submit" class="btn btn-dark">Save</button>
    </form>
</div>
{% endblock body %}

post/templates/post/index.html
{% extends 'post/base.html' %}

{% block body %}


{% endblock body %}

post/templates/post/navbar.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class=" container-fluid">
        <a class="navbar-brand" href="{% url 'post:home' %}" style="color:black">BlogPost</a>
        <ul class="nav justify-content-end">

            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:profile' %}">profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'post:add_post' %}">Add A post</a>
            </li>

            {% endif %}
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
                {% else %}
                <a class="nav-link" href="{% url 'auth:register' %}">register</a>
                {% endif %}
            </li>

        </ul>
    </div>
</nav>

post/templates/post/posts.html
{% extends 'post/base.html' %}

{% block body %}
<h1 style="text-align: center;"><i>Posts</i></h1>
{% if posts %}
{% for post in posts %}

<div class="container-sm">
    <div class="shadow p-2 mb-5 bg-body rounded " style="margin-bottom: 5px;">
        <h5 class="mb-1"><a href="{% url 'post:details' post.id %}">{{post.title}}</a></h5>


        <p class="mb-0">{{post.content|slice:":100"|safe}}...</p>
    </div>
</div>

{% endfor %}

{% else %}
<h2 style="text-align: center;"> No Posts </h2>
{% endif %}


{% endblock body %}

post/templates/post/w_posts.html
{% extends 'post/base.html' %}
{% block body %}
<div class="container-md">

    <form action="{% url 'post:add_post'%}" method="post">
        {% csrf_token %}
        <br>
        <div class="row justify-content-md-center">{{form.title}}</div>
        <br>
        <div class="row justify-content-md-center">
            {{form.content}}
        </div>
        <br>
        <button type="submit" class="btn btn-dark">submit</button>
    </form>
</div>

{% endblock body %}